### ISSUE TITLE
Error with running scripts

### ISSUE THREAD

**Issue by Romk-a** [kNalj/sipsimple3-examples#1]
I have built sipsimple 5.3.0 and am trying to run your examples. But something is going wrong. I think the code in the latest versions of sipsimple has changed and these examples no longer work. I am new to python. Could you please help me to fix this error?

```
(.sipsimple-venv) romk@romk~/asr-caller$ /home/romk/asr-caller/.sipsimple-venv/bin/python /home/romk/asr-caller/ConfigCall.py.py
Placing call, press Enter to quit the program
None
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/sipsimple/application.py", line 141, in _run_reactor
    reactor.run(installSignalHandlers=False)
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/twisted/internet/base.py", line 695, in run
    self.mainLoop()
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/twisted/internet/base.py", line 705, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/twisted/internet/base.py", line 1090, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/eventlib/api.py", line 241, in _spawn
    g.switch()
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/eventlib/api.py", line 237, in _spawn_startup
    return cb(*args, **kw)
  File "/home/romk/asr-caller/.sipsimple-venv/lib/python3.11/site-packages/sipsimple/session.py", line 1051, in connect
    self._local_identity = FromHeader(self.account.uri, self.account.display_name)
builtins.AttributeError: 'NoneType' object has no attribute 'uri'
```

**Comment by Romk-a** [comment]
The problem was that I didn't have my account set up correctly. I created a config file with the default account settings and that solved my problem.
